nxos/base/lib/rcmd: Fix no-op.
It looks like this was originally intended to suppress unused argument warnings, but it introduces new warnings about unused variables.

Fixes:

base/lib/rcmd/rcmd.c: In function 'nx_rcmd_clear':
base/lib/rcmd/rcmd.c:174:8: error: variable 'c' set but not used [-Werror=unused-but-set-variable]
  174 |   char c;
      |        ^
base/lib/rcmd/rcmd.c: In function 'nx_rcmd_nop':
base/lib/rcmd/rcmd.c:245:8: error: variable 'c' set but not used [-Werror=unused-but-set-variable]
  245 |   char c;
      |        ^