Revert "ev3dev: set custom sys.platform name"
This reverts commit 3771df276070ef08519c712a7cd1707993899e45.

Apparently, this breaks things:

```
>>> import pybricks.ev3brick as ev3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pybricks/ev3brick.py", line 38, in <module>
  File "pybricks/speaker.py", line 26, in <module>
  File "pybricks/uev3dev/sound.py", line 24, in <module>
  File "os/os/__init__.py", line 32, in <module>
  File "ffilib/ffilib.py", line 37, in libc
  File "ffilib/ffilib.py", line 34, in open
  File "ffilib/ffilib.py", line 29, in open
OSError: [Errno 2] ENOENT
```

https://github.com/micropython/micropython-lib/blob/f20d89c6aad9443a696561ca2a01f7ef0c8fb302/ffilib/ffilib.py#L17