nxos/base/types: Fix conflicting types for size_t.
Let stddef.h provide it.

Fixes:

/usr/share/gcc-arm-none-eabi-10-2020-q4-major/lib/gcc/arm-none-eabi/10.2.1/include/stddef.h:209:23: error: conflicting types for 'size_t'
  209 | typedef __SIZE_TYPE__ size_t;
      |                       ^~~~~~
In file included from base/lib/memalloc/memalloc.c:9:
./base/types.h:26:13: note: previous declaration of 'size_t' was here
   26 | typedef U32 size_t; /**< Abstract size type, needed by the memory allocator. */
      |             ^~~~~~
In file included from base/lib/memalloc/memalloc.c:23:
./base/lib/memalloc/_tlsf.c.inc: In function 'FIND_SUITABLE_BLOCK':
./base/lib/memalloc/_tlsf.c.inc:236:47: error: left shift of negative value [-Werror=shift-negative-value]
  236 |     u32_t _tmp = _tlsf->sl_bitmap[*_fl] & (~0 << *_sl);
      |                                               ^~
./base/lib/memalloc/_tlsf.c.inc:243:40: error: left shift of negative value [-Werror=shift-negative-value]
  243 |   *_fl = ls_bit(_tlsf->fl_bitmap & (~0 << (*_fl + 1)));
      |                                        ^~
cc1: all warnings being treated as errors
scons: *** [base/lib/memalloc/memalloc.o] Error 1
scons: building terminated because of errors.