drv/ev3dev_stretch/ev3sensor: fix missing format specifier
Fixes compile error with newer GCC

../../../../ports/pybricks/lib/pbio/drv/ev3dev_stretch/ev3sensor.c: In function ‘pbdrv_ev3_sensor_set_mode’:
../../../../ports/pybricks/lib/pbio/drv/ev3dev_stretch/ev3sensor.c:234:5: error: format not a string literal and no format arguments [-Werror=format-security]
     if (fprintf(sensor->f_mode, sysfs_mode) != strlen(sysfs_mode)) {
     ^~