bricks/ev3dev/pb_type_ev3dev_image: fix uninitialized field
When -Wextra is enabled, this was causing:

    pb_type_ev3dev_image.c:75:9: error: missing initializer for field ‘defval’ of ‘mp_arg_t’ {aka ‘const struct _mp_arg_t’} [-Werror=missing-field-initializers]
    75 |         { MP_QSTR_source, MP_ARG_REQUIRED | MP_ARG_OBJ },
        |