error: add PBIO_ERROR_INVALID_OP
This is intended for cases when an operation is supported, but is not valid given the current state of the program. For example when a UART device mode is set to a certain mode and we try to do somthing that mode does not allow.

MOVEHUB fw size +32