github: fix typo in download-commit-metadata.py
There was an extra trailing comma inside the string "essentialhub".

This was causing the "Stats" CI task to fail with:

    Client-Request-ID=827c8092-1630-11ec-8f90-57a053a78575 Retry policy did not allow for a retry: Server-Timestamp=Wed, 15 Sep 2021 14:23:34 GMT, Server-Request-ID=28a86b1b-6002-009a-073d-aa1971000000, HTTP status code=400, Exception=Bad Request{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"An identifier was expected at position 65.\nRequestId:28a86b1b-6002-009a-073d-aa1971000000\nTime:2021-09-15T14:23:34.8381644Z"}}}.
    Traceback (most recent call last):
    File ".github/download-commit-metadata.py", line 96, in <module>
        main()
    File ".github/download-commit-metadata.py", line 53, in main
        for item in service.query_entities(
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/tableservice.py", line 738, in query_entities
        resp = self._query_entities(*args, **kwargs)
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/tableservice.py", line 801, in _query_entities
        return self._perform_request(request, _convert_json_response_to_entities,
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/tableservice.py", line 1106, in _perform_request
        return super(TableService, self)._perform_request(request, parser, parser_args, operation_context)
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/common/storageclient.py", line 430, in _perform_request
        raise ex
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/common/storageclient.py", line 358, in _perform_request
        raise ex
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/common/storageclient.py", line 343, in _perform_request
        _http_error_handler(
    File "/home/david/work/pybricks/pybricks-micropython/.venv/lib/python3.8/site-packages/azure/cosmosdb/table/common/_error.py", line 115, in _http_error_handler
        raise ex
    azure.common.AzureHttpError: Bad Request
    {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"An identifier was expected at position 65.\nRequestId:28a86b1b-6002-009a-073d-aa1971000000\nTime:2021-09-15T14:23:34.8381644Z"}}}

Fixes: f8bdc651