pberror: rename pb_raise_pbio_error() to pb_assert() and simplify calls
pb_assert is shorter, which is nice when using this inline. Also "assert" is a pythonic way to say "conditionally raise an exception"

removing  error parameter in wait_for_completion() in modmotor.c does not change program flow, so it is deleted

MOVEHUB fw size -24