modtools: add kwarg for wait
Now both allowed:
wait(1000)
wait(time=1000)

Now gives a more descriptive error:
>>> wait()
TypeError: 'time' argument required