pbdrv/light: fix light when color not available
hub.light.on(Color.BLACK)

and others, gave:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid argument

But the docs say that unavailable colors should tur the light off, which makes sense especially for Color.BLACK.

This could be done at a higher code level, but this takes the least amount of space, and lights still need to be revised as a whole.