pbio/button: fix compile when PBDRV_CONFIG_BUTTON == 0
when the button driver is disabled, we get the following error because
the definition of pbio_button_is_pressed() doesn't match
pbdrv_button_is_pressed().  The defintion is  just for documentation,
so handle it as such.

../include/pbdrv/button.h:58:28: error: static declaration of ‘pbdrv_button_is_pressed’ follows non-static declaration
 static inline pbio_error_t pbdrv_button_is_pressed(pbio_button_flags_t *pressed) {
                            ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/pbdrv/button.h:16:0,
                 from ../src/main.c:11:
../include/pbio/button.h:98:32: note: previous declaration of ‘pbdrv_button_is_pressed’ was here
                                ^
../include/pbio/button.h:112:14: note: in expansion of macro ‘pbio_button_is_pressed’
 pbio_error_t pbio_button_is_pressed(pbio_button_flags_t *pressed);
              ^~~~~~~~~~~~~~~~~~~~~~