nxos/base/drivers/i2c: Supress unused variable warning.
The comment indicates that this read operation is intentional, so keep it.

Instead just cast to void to suppress:

base/drivers/i2c.c:410:16: error: variable 'dummy' set but not used [-Werror=unused-but-set-variable]
  410 |   volatile U32 dummy;
      |                ^~~~~