Makefile: ensure mpy-cross is built for host arch
The ev3dev-armel docker images sets the CROSS_COMPILE environment
variable, so we need to unset it when compiling mpy-cross. Otherwise
mpy-cross is compiled for ARM instead of x86_64.

If docker is configured to run foreign arch via QEMU, this problem
would go unnoticed. But if not, it caused the following error:

    MPY core.py
    Traceback (most recent call last):
    File "../../micropython/tools/makemanifest.py", line 350, in <module>
        main()
    File "../../micropython/tools/makemanifest.py", line 287, in main
        + ["-o", outfile, "-s", script, "-O{}".format(opt), infile]
    File "../../micropython/tools/makemanifest.py", line 134, in system
        output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    OSError: [Errno 8] Exec format error