update with rust and libjpg install to
new build environment and found some requirements for successful build not listed.

ERROR: Could not build wheels for cryptography requires Rust >=1.41.0
libjpeg, a required dependency when compiling Pillow from source.